# numpy

### reference 

NumPy 教程 | 菜鸟教程
http://www.runoob.com/numpy/numpy-tutorial.html
    
Python Numpy Tutorial
http://cs231n.github.io/python-numpy-tutorial/    

### numpy

数组与矩阵运算, 
主要包含: 
NumPy 最重要的一个特点: 一个强大的N维数组对象 ndarray

NumPy 通常与 SciPy（Scientific Python）和 Matplotlib（绘图库）一起使用， 这种组合广泛用于替代 MatLab，是一个强大的科学计算环境.

SciPy 是一个开源的 Python 算法库和数学工具包。


### numpy.array 

ndarray 对象是用于存放同类型元素的多维数组。

#### ndarray.shape 

一个表示数组形状（shape）的元组，表示各维度大小的元组。

In [2]:
# 一维
import numpy as np 
a = np.array([1,2,3])  
print (a)

[1 2 3]


In [3]:
# 2维
import numpy as np 
a = np.array([[1,  2],  [3,  4]])  
print (a)

[[1 2]
 [3 4]]


### numpy.arange

从数值范围创建数组


In [4]:
import numpy as np
 
x = np.arange(5)  
print (x)

[0 1 2 3 4]


### 切片

In [5]:
import numpy as np
 
a = np.arange(10)
s = slice(2,7,2)   # 从索引 2 开始到索引 7 停止，间隔为2
print (a[s])

[2 4 6]


In [6]:
import numpy as np
 
a = np.arange(10)  
b = a[2:7:2]   # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]


In [7]:
import numpy as np
 
a = np.arange(10)
print(a[2:])

[2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
 
a = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]
print(a[2:5])

[2 3 4]
